### PR TITLE
RNN with LSTM-Neural Network

### PR DESCRIPTION
**Pull request by codingCapricorn**
RNN with LSTM-Neural Network

### CODE REVIEW

**Comment by Praful932** [comment]
Hello @codingCapricorn. Could you change the format to a Jupyter Notebook one? and also squash your commits. I can merge your PR then.

**Comment by codingCapricorn** [comment]
RNN With LSTM-Neural Networks :::
As you requested ,I have merged the file with jupyter notebook format and also squashed the comments.You can merge the PR now.

**Comment by Praful932** [comment]
I think you misunderstood the squash part. You have 8 commits total, could you squash into one. Check [this](https://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request). Then I can merge your PR.

**Comment by codingCapricorn** [comment]
Hey @Praful932 .... Is there any way to squash all commits into one using github web application itself rather than writing commands on CLI ? I am not aware of how to squash all commits into one.please guide me.

**Comment by Praful932** [comment]
@codingCapricorn You can use [GitKraken](https://www.gitkraken.com/) GUI to squash commits. Follow the tutorial [here ](https://youtu.be/cr1N8VTRmfM)after installing it.

**Comment by Praful932** [comment]
@codingCapricorn Updates?

**Comment by codingCapricorn** [comment]
Unable to install gitkaren on my PC.

**Comment by Praful932** [comment]
@codingCapricorn Use these commands after cloning the repo in the directory in git bash or any CLI
`git reset --soft HEAD~8`
`git commit`

**Comment by Praful932** [comment]
Closed due to inactivity.

**Pull request closed without merging**
